BploSection::Settings::RequiredDocument.find_or_create_by(name: "Barangay Clearance", default_requirement: true)
BploSection::Settings::RequiredDocument.find_or_create_by(name: "Barangay Business Clearance", default_requirement: true)
BploSection::Settings::RequiredDocument.find_or_create_by(name: "Residence Certificate(Cedula)", default_requirement: true)
BploSection::Settings::RequiredDocument.find_or_create_by(name: "2 pcs. 2x2 ID Picture", default_requirement: true)
BploSection::Settings::RequiredDocument.find_or_create_by(name: "Police Clearance", default_requirement: true)
BploSection::Settings::RequiredDocument.find_or_create_by(name: "Sanitary Permit", default_requirement: true)
BploSection::Settings::RequiredDocument.find_or_create_by(name: "Engineering Clearance", default_requirement: true)
BploSection::Settings::RequiredDocument.find_or_create_by(name: "Fire Safety Inspection Certificate", default_requirement: true)
BploSection::Settings::RequiredDocument.find_or_create_by(name: "Occupancy Permit")
BploSection::Settings::RequiredDocument.find_or_create_by(name: "Sanitary Permit")
BploSection::Settings::RequiredDocument.find_or_create_by(name: "Health Clearance")
BploSection::Settings::RequiredDocument.find_or_create_by(name: "Market Clearance")
BploSection::Settings::RequiredDocument.find_or_create_by(name: "BFAD Permit")
BploSection::Settings::RequiredDocument.find_or_create_by(name: "Videoke Task Force Compliance Certificate")
BploSection::Settings::RequiredDocument.find_or_create_by(name: "Zoning/Locational Clearance")
