TricycleFee.find_or_create_by(name: "Mayor's Permit", amount: 231.00, default_fee: true)
TricycleFee.find_or_create_by(name: "Filing Fee", amount: 165.00)
TricycleFee.find_or_create_by(name: "Parking Fee", amount: 165.00, default_fee: true)
TricycleFee.find_or_create_by(name: "Franchise Fee", amount: 75.00, default_fee: true)
TricycleFee.find_or_create_by(name: "MTOP Plate", amount: 120.00)
TricycleFee.find_or_create_by(name: "Sticker Fee", amount: 55.00)
