TricycleOrganization.find_or_create_by(abbreviated_name: "HTTODA", name: "Hapid Tupaya Tricycle Operators and Drivers Association")
TricycleOrganization.find_or_create_by(abbreviated_name: "NPBTODA", name: "Nayon Payawan Bimpal Tricycle Operators and Drivers Association")
TricycleOrganization.find_or_create_by(abbreviated_name: "LCATODA", name: "Lamut Cockpit Arena Tricycle Operators and Drivers Association")
TricycleOrganization.find_or_create_by(abbreviated_name: "PIEZATODA", name: "Pieza Tricycle Operators and Drivers Association")
TricycleOrganization.find_or_create_by(abbreviated_name: "PTODA", name: "Pugol Tricycle Operators and Drivers Association")
TricycleOrganization.find_or_create_by(abbreviated_name: "LAGSATODA", name: "LAGSADECO Tricycle Operators and Drivers Association")
TricycleOrganization.find_or_create_by(abbreviated_name: "LAMLAWTODA", name: "Lamut Lawig Tricycle Operators and Drivers Association")
TricycleOrganization.find_or_create_by(abbreviated_name: "TPLTODA", name: "Turod Panopdopan Lucban Tricycle Operators and Drivers Association")
TricycleOrganization.find_or_create_by(abbreviated_name: "SF-NMART-TODA", name: "San Francisco NMART Tricycle Operators and Drivers Association")
TricycleOrganization.find_or_create_by(abbreviated_name: "SMTODA", name: "Salamague Tricycle Operators and Drivers Association")
TricycleOrganization.find_or_create_by(abbreviated_name: "LAMTODA", name: "Lamut Tricycle Operators and Drivers Association")
TricycleOrganization.find_or_create_by(abbreviated_name: "MAGLONTODA", name: "Magulon Tricycle Operators and Drivers Association")
TricycleOrganization.find_or_create_by(abbreviated_name: "MATODA", name: "Mabatobato Tricycle Operators and Drivers Association")
TricycleOrganization.find_or_create_by(abbreviated_name: "CENTROTODA", name: "Centro Tricycle Operators and Drivers Association")
TricycleOrganization.find_or_create_by(abbreviated_name: "PSBTODA", name: "Sanafe Bulao Tricycle Operators and Drivers Association")
