municipality = Addresses::MunicipalityOrCity.find_by(name: "Lamut")
municipality.barangays.find_or_create_by(name: "Ambasa")
municipality.barangays.find_or_create_by(name: "Bimpal")
municipality.barangays.find_or_create_by(name: "Hapid")
municipality.barangays.find_or_create_by(name: "Holowon")
municipality.barangays.find_or_create_by(name: "Lawig")
municipality.barangays.find_or_create_by(name: "Lucban")
municipality.barangays.find_or_create_by(name: "Mabatobato")
municipality.barangays.find_or_create_by(name: "Magulon")
municipality.barangays.find_or_create_by(name: "Nayon")
municipality.barangays.find_or_create_by(name: "Panopdopan")
municipality.barangays.find_or_create_by(name: "Payawan")
municipality.barangays.find_or_create_by(name: "Pieza")
municipality.barangays.find_or_create_by(name: "Poblacion East")
municipality.barangays.find_or_create_by(name: "Poblacion West")
municipality.barangays.find_or_create_by(name: "Pugol")
municipality.barangays.find_or_create_by(name: "Salamague")
municipality.barangays.find_or_create_by(name: "Sanafe")
municipality.barangays.find_or_create_by(name: "Umilag")
